#!/usr/bin/env python3
"""
Controlled Strategy Research Study
===================================
Executes all 10 research tasks without modifying production code.

Tasks:
1. Validate the diagnostic itself
2. Reconcile the strategy contradiction
3. Diagnose the stop-loss problem
4. Diagnose the take-profit problem
5. Test modifications one at a time (ablation experiments A-G)
6. Out-of-sample testing
7. Test all five assets separately and together
8. Challenge-specific simulation
9. Decision criteria evaluation
10. Final recommendation

All data is SYNTHETIC. No production conclusions should be drawn
from synthetic-only scenarios.
"""
from __future__ import annotations

import sys
import os
import json
from dataclasses import asdict
from io import StringIO

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.strategy.engine import StrategyEngine
from src.strategy.challenge_engine import ChallengeStrategyEngine
from src.strategy.indicators import compute_indicators
from src.strategy.regime import classify_regime, MarketRegime
from src.strategy.backtester import run_backtest, run_monte_carlo

from research.data_generator import generate_all_assets, ASSET_PROFILES
from research.enhanced_backtester import run_enhanced_backtest, DetailedTrade
from research.experimental_engines import (
    ExperimentB_NoCHOP,
    ExperimentC_TrendOnly,
    ExperimentD_TP2R,
    ExperimentE_TP1_5R,
    ExperimentF_GraduatedRisk,
    ExperimentG_EarlyTrend,
)

ASSETS = list(ASSET_PROFILES.keys())
N_DAYS = 800
TRAIN_END = 400
VAL_END = 600
TEST_START = 600

report = StringIO()


def log(msg: str = ""):
    print(msg)
    report.write(msg + "\n")


def fmt_pct(val: float) -> str:
    return f"{val * 100:.2f}%"


def fmt_usd(val: float) -> str:
    return f"${val:.2f}"


def task_1_validate_diagnostic(all_data: dict[str, pd.DataFrame]):
    log("\n" + "=" * 80)
    log("TASK 1: VALIDATE THE DIAGNOSTIC")
    log("=" * 80)

    log("\n--- Data Provenance ---")
    log("Data type:        SYNTHETIC (generated by research/data_generator.py)")
    log("Data provider:    None — no external API calls")
    log("                  (Coinbase/Kraken APIs blocked by network policy)")
    log("Candle timeframe: Daily (1D)")
    log("")

    for symbol, df in all_data.items():
        enriched = compute_indicators(df)
        log(f"\n  {symbol}:")
        log(f"    Total candles:     {len(df)}")
        log(f"    Date range:        {df['open_time'].iloc[0].date()} to {df['open_time'].iloc[-1].date()}")
        log(f"    Tradeable candles: {len(df) - 200} (after 200-candle warmup)")
        log(f"    Base price:        {ASSET_PROFILES[symbol]['base_price']}")
        log(f"    Final price:       {df['close'].iloc[-1]:.2f}")
        log(f"    Price range:       {df['low'].min():.2f} — {df['high'].max():.2f}")

    log("\n--- Indicator Look-Ahead Bias Check ---")
    log("All indicators use strictly backward-looking operations:")
    log("  - EMA: ewm(adjust=False) — recursive, no future data")
    log("  - ER20: shift(20) and rolling(20) — backward only")
    log("  - ADX14: ewm on historical DM/TR — backward only")
    log("  - RVol: rolling(20).std() — backward only")
    log("  - rvol_median_252: rolling(60).median() — backward only")
    log("  - price_change_48h: pct_change(2) — backward only")
    log("  - price_change_short: pct_change(1) — backward only")
    log("  VERDICT: No look-ahead bias detected.")

    log("\n--- Trade Execution Timing ---")
    log("  Indicators computed on full history ONCE (safe: all ops backward-looking)")
    log("  Signals generated using window ending at current day (inclusive)")
    log("  Entry: at day's close price * (1 + commission + spread)")
    log("  Stop/TP: checked against next day's high/low BEFORE new signals")
    log("  Same-bar entry+stop impossible (stops checked before new entries)")
    log("  VERDICT: No same-candle signal-and-trade bias.")

    log("\n--- Cost Assumptions ---")
    log(f"  Commission:   0.26% per side")
    log(f"  Spread:       0.10% per side")
    log(f"  Total RT:     ~0.72%")
    log(f"  Slippage:     implicit in spread assumption")

    log("\n--- Position Handling ---")
    log("  Max simultaneous positions: 2 (conservative) / 3 (challenge)")
    log("  Multiple assets tested sequentially per symbol (not portfolio)")
    log("  Challenge result from equity = cash balance + realized PnL")
    log("  Open positions force-closed at end of data")

    log("\n--- CRITICAL LIMITATION ---")
    log("  *** ALL DATA IS SYNTHETIC ***")
    log("  Results reflect strategy behavior on modeled price paths,")
    log("  NOT real historical market outcomes.")
    log("  No production conclusions should be drawn.")


def task_2_reconcile_contradiction(all_data: dict[str, pd.DataFrame]):
    log("\n" + "=" * 80)
    log("TASK 2: RECONCILE THE STRATEGY CONTRADICTION")
    log("=" * 80)

    log("\n--- Root Cause Analysis ---")
    log("")
    log("The strategy description says 'BUY requires confirmed trend and price above EMA200.'")
    log("The code (engine.py _check_buy_conditions) actually requires:")
    log("  1. regime != PANIC")
    log("  2. balance in [$975, $1110)")
    log("  3. price >= EMA200")
    log("  4. previous candle close > previous candle EMA50")
    log("  5. |price_change_short| <= 8%")
    log("  6. open positions < max")
    log("  7. no existing position in this symbol")
    log("  8. risk budget allows")
    log("")
    log("CRITICALLY: The code does NOT require regime == TREND for entry.")
    log("It allows CHOP and LOWVOL entries with reduced risk/tighter stops:")
    log("  - TREND:  0.3% risk, 3.0% stop")
    log("  - CHOP:   0.25% risk, 2.5% stop")
    log("  - LOWVOL: 0.25% risk, 2.0% stop")
    log("")
    log("Only at balance >= $1090 does the code restrict to TREND-only.")
    log("")
    log("VERDICT: The strategy INTENTIONALLY permits CHOP/LOWVOL entries.")
    log("This is not a bug — it's a design mismatch between the specification")
    log("document and the implemented code. The specification is misleading.")
    log("Production and backtest use the SAME engine code (StrategyEngine).")

    log("\n--- Detailed Trade Log (all assets, full period) ---\n")
    log(f"{'#':>3} {'Asset':<9} {'Entry Date':<12} {'Regime':<8} {'Entry':>10} "
        f"{'EMA50':>10} {'EMA200':>10} {'ER20':>6} {'ADX14':>6} "
        f"{'Stop':>10} {'TP':>10} {'Size':>8} {'Exit':>10} {'P&L':>8}")
    log("-" * 145)

    trade_num = 0
    regime_counts = {"TREND": 0, "CHOP": 0, "LOWVOL": 0, "PANIC": 0}

    for symbol in ASSETS:
        engine = StrategyEngine()
        result = run_enhanced_backtest(engine, symbol, all_data[symbol], "Conservative")

        for t in result.trades:
            trade_num += 1
            regime = t.regime_at_entry
            if regime in regime_counts:
                regime_counts[regime] += 1

            entry_date = t.entry_date[:10] if len(t.entry_date) > 10 else t.entry_date
            log(f"{trade_num:>3} {symbol:<9} {entry_date:<12} {regime:<8} "
                f"{t.entry_price:>10.2f} {t.ema50_at_entry:>10.2f} "
                f"{t.ema200_at_entry:>10.2f} {t.er20_at_entry:>6.3f} "
                f"{t.adx14_at_entry:>6.1f} {t.stop_loss:>10.2f} "
                f"{t.take_profit:>10.2f} {t.position_value:>8.2f} "
                f"{t.exit_reason:<10} {t.pnl:>+8.2f}")

    log(f"\nTotal trades across all assets: {trade_num}")
    log(f"Regime breakdown at entry:")
    for r, c in sorted(regime_counts.items()):
        pct = c / trade_num * 100 if trade_num > 0 else 0
        log(f"  {r}: {c} ({pct:.1f}%)")


def task_3_diagnose_stoploss(all_data: dict[str, pd.DataFrame]):
    log("\n" + "=" * 80)
    log("TASK 3: DIAGNOSE THE STOP-LOSS PROBLEM")
    log("=" * 80)

    all_losses = []
    for symbol in ASSETS:
        engine = StrategyEngine()
        result = run_enhanced_backtest(engine, symbol, all_data[symbol], "Conservative")
        for t in result.trades:
            if t.pnl <= 0:
                all_losses.append(t)

    log(f"\nTotal losing trades: {len(all_losses)}")
    log(f"\n{'#':>3} {'Asset':<9} {'Regime':<8} {'MFE%':>7} {'MAE%':>7} "
        f"{'Candles':>7} {'Recovered':>9} {'ATR':>8} {'Stop/ATR':>8} "
        f"{'Category':<20}")
    log("-" * 110)

    categories = {
        "wrong_direction": 0,
        "stop_too_tight": 0,
        "entry_bad_regime": 0,
        "price_noise": 0,
        "late_entry": 0,
        "other": 0,
    }

    for i, t in enumerate(all_losses, 1):
        mfe_pct = t.max_favorable_excursion * 100
        mae_pct = t.max_adverse_excursion * 100
        stop_pct = t.stop_distance_pct * 100

        if t.max_favorable_excursion < 0.005 and not t.price_recovered_after_stop:
            category = "wrong_direction"
        elif t.price_recovered_after_stop and t.candles_to_exit <= 3:
            category = "price_noise"
        elif t.price_recovered_after_stop and t.stop_as_atr_multiple < 1.0:
            category = "stop_too_tight"
        elif t.regime_at_entry in ("CHOP", "LOWVOL"):
            category = "entry_bad_regime"
        elif t.price_recovered_after_stop:
            category = "stop_too_tight"
        else:
            category = "other"

        categories[category] += 1

        log(f"{i:>3} {t.symbol:<9} {t.regime_at_entry:<8} {mfe_pct:>6.2f}% "
            f"{mae_pct:>6.2f}% {t.candles_to_exit:>7} "
            f"{'YES' if t.price_recovered_after_stop else 'NO':>9} "
            f"{t.atr14_at_entry:>8.2f} {t.stop_as_atr_multiple:>8.2f} "
            f"{category:<20}")

    log(f"\n--- Loss Category Summary ---")
    for cat, count in sorted(categories.items(), key=lambda x: -x[1]):
        pct = count / len(all_losses) * 100 if all_losses else 0
        log(f"  {cat:<20} {count:>3} ({pct:.1f}%)")

    recovered = sum(1 for t in all_losses if t.price_recovered_after_stop)
    log(f"\nPrice recovered within 30 candles after stop: {recovered}/{len(all_losses)} "
        f"({recovered / len(all_losses) * 100:.1f}%)" if all_losses else "")

    if all_losses:
        avg_mae = np.mean([t.max_adverse_excursion for t in all_losses])
        avg_mfe = np.mean([t.max_favorable_excursion for t in all_losses])
        avg_stop_atr = np.mean([t.stop_as_atr_multiple for t in all_losses if t.stop_as_atr_multiple > 0])
        log(f"\nAverage MFE before stop: {avg_mfe * 100:.2f}%")
        log(f"Average MAE at stop:     {avg_mae * 100:.2f}%")
        log(f"Average stop/ATR ratio:  {avg_stop_atr:.2f}")


def task_4_diagnose_takeprofit(all_data: dict[str, pd.DataFrame]):
    log("\n" + "=" * 80)
    log("TASK 4: DIAGNOSE THE TAKE-PROFIT PROBLEM")
    log("=" * 80)

    all_trades = []
    for symbol in ASSETS:
        engine = StrategyEngine()
        result = run_enhanced_backtest(engine, symbol, all_data[symbol], "Conservative")
        all_trades.extend(result.trades)

    log(f"\nTotal trades: {len(all_trades)}")
    log(f"\n{'#':>3} {'Asset':<9} {'MFE%':>7} {'1R':>4} {'1.5R':>5} {'2R':>4} "
        f"{'3R':>4} {'C→1R':>5} {'C→1.5R':>6} {'C→2R':>5} {'C→3R':>5} {'Exit':>10} {'P&L':>8}")
    log("-" * 100)

    for i, t in enumerate(all_trades, 1):
        mfe_pct = t.max_favorable_excursion * 100
        log(f"{i:>3} {t.symbol:<9} {mfe_pct:>6.2f}% "
            f"{'Y' if t.reached_1r else 'N':>4} "
            f"{'Y' if t.reached_1_5r else 'N':>5} "
            f"{'Y' if t.reached_2r else 'N':>4} "
            f"{'Y' if t.reached_3r else 'N':>4} "
            f"{t.candles_to_1r if t.reached_1r else '-':>5} "
            f"{t.candles_to_1_5r if t.reached_1_5r else '-':>6} "
            f"{t.candles_to_2r if t.reached_2r else '-':>5} "
            f"{t.candles_to_3r if t.reached_3r else '-':>5} "
            f"{t.exit_reason:<10} {t.pnl:>+8.2f}")

    # Alternative exit analysis
    log("\n--- Alternative Exit Policy Comparison ---\n")

    exit_policies = {
        "Current (3R)": {"tp_mult": 3.0},
        "2R target": {"tp_mult": 2.0},
        "1.5R target": {"tp_mult": 1.5},
        "1R + trail": {"tp_mult": 1.0, "trailing": True},
    }

    log(f"{'Policy':<20} {'Win%':>6} {'Avg Win':>8} {'Avg Loss':>9} "
        f"{'Expect':>8} {'PF':>6} {'Total PnL':>10}")
    log("-" * 75)

    for policy_name, params in exit_policies.items():
        tp_mult = params["tp_mult"]
        wins_count = 0
        losses_count = 0
        win_pnls = []
        loss_pnls = []

        for t in all_trades:
            risk_unit = t.stop_distance_pct * t.entry_price if t.entry_price > 0 else 0
            if risk_unit <= 0:
                continue

            if t.exit_reason == "stop_loss":
                tp_target = t.entry_price + risk_unit * tp_mult / t.stop_distance_pct * t.stop_distance_pct
                mfe_price = t.entry_price * (1 + t.max_favorable_excursion)

                if mfe_price >= t.entry_price + risk_unit * tp_mult:
                    sim_exit = t.entry_price + risk_unit * tp_mult
                    cost = t.position_value * 0.0036
                    sim_pnl = t.position_value * (sim_exit - t.effective_entry) / t.effective_entry - cost
                    if sim_pnl > 0:
                        wins_count += 1
                        win_pnls.append(sim_pnl)
                    else:
                        losses_count += 1
                        loss_pnls.append(sim_pnl)
                else:
                    losses_count += 1
                    loss_pnls.append(t.pnl)
            elif t.exit_reason == "take_profit":
                risk_unit_actual = t.risk_dollars
                sim_pnl_val = risk_unit_actual * tp_mult
                cost = t.position_value * 0.0036
                sim_pnl = sim_pnl_val - cost
                if sim_pnl > 0:
                    wins_count += 1
                    win_pnls.append(sim_pnl)
                else:
                    losses_count += 1
                    loss_pnls.append(sim_pnl)
            else:
                if t.pnl > 0:
                    wins_count += 1
                    win_pnls.append(t.pnl)
                else:
                    losses_count += 1
                    loss_pnls.append(t.pnl)

        total = wins_count + losses_count
        wr = wins_count / total if total > 0 else 0
        avg_w = np.mean(win_pnls) if win_pnls else 0
        avg_l = np.mean(loss_pnls) if loss_pnls else 0
        expectancy = wr * avg_w + (1 - wr) * avg_l
        gross_w = sum(win_pnls)
        gross_l = abs(sum(loss_pnls))
        pf = gross_w / gross_l if gross_l > 0 else float('inf')
        total_pnl = sum(win_pnls) + sum(loss_pnls)

        log(f"{policy_name:<20} {wr * 100:>5.1f}% {avg_w:>+8.2f} {avg_l:>+9.2f} "
            f"{expectancy:>+8.2f} {pf:>6.2f} {total_pnl:>+10.2f}")


def run_ablation_experiment(engine, name, all_data, period_slice=None):
    results_by_asset = {}
    for symbol in ASSETS:
        df = all_data[symbol]
        if period_slice:
            df = df.iloc[period_slice].reset_index(drop=True)
        if len(df) < 210:
            continue
        result = run_enhanced_backtest(engine, symbol, df, name)
        results_by_asset[symbol] = result
    return results_by_asset


def summarize_experiment(name, results_by_asset):
    total_trades = 0
    total_wins = 0
    total_losses = 0
    total_pnl = 0.0
    max_dd = 0.0
    all_pnls = []

    for symbol, r in results_by_asset.items():
        total_trades += r.total_trades
        total_wins += r.wins
        total_losses += r.losses
        total_pnl += r.total_pnl
        max_dd = max(max_dd, r.max_drawdown_pct)
        for t in r.trades:
            all_pnls.append(t.pnl)

    wr = total_wins / total_trades if total_trades > 0 else 0
    avg_win = np.mean([p for p in all_pnls if p > 0]) if any(p > 0 for p in all_pnls) else 0
    avg_loss = np.mean([p for p in all_pnls if p <= 0]) if any(p <= 0 for p in all_pnls) else 0
    expectancy = wr * avg_win + (1 - wr) * avg_loss if total_trades > 0 else 0
    gross_w = sum(p for p in all_pnls if p > 0)
    gross_l = abs(sum(p for p in all_pnls if p <= 0))
    pf = gross_w / gross_l if gross_l > 0 else float('inf')

    return {
        "name": name,
        "trades": total_trades,
        "wins": total_wins,
        "losses": total_losses,
        "win_rate": wr,
        "avg_win": avg_win,
        "avg_loss": avg_loss,
        "expectancy": expectancy,
        "profit_factor": pf,
        "total_pnl": total_pnl,
        "max_drawdown": max_dd,
    }


def task_5_ablation_experiments(all_data):
    log("\n" + "=" * 80)
    log("TASK 5: ABLATION EXPERIMENTS (A through G)")
    log("=" * 80)

    experiments = {
        "A: Baseline": StrategyEngine(),
        "B: No CHOP": ExperimentB_NoCHOP(),
        "C: TREND only": ExperimentC_TrendOnly(),
        "D: TP at 2R": ExperimentD_TP2R(),
        "E: TP at 1.5R": ExperimentE_TP1_5R(),
        "F: Graduated risk": ExperimentF_GraduatedRisk(),
        "G: Early Trend": ExperimentG_EarlyTrend(),
    }

    summaries = []
    for exp_name, engine in experiments.items():
        results = run_ablation_experiment(engine, exp_name, all_data)
        summary = summarize_experiment(exp_name, results)
        summaries.append(summary)

    log(f"\n{'Experiment':<22} {'Trades':>6} {'Win%':>6} {'AvgWin':>8} {'AvgLoss':>8} "
        f"{'Expect':>8} {'PF':>6} {'PnL':>9} {'MaxDD':>7}")
    log("-" * 95)

    for s in summaries:
        log(f"{s['name']:<22} {s['trades']:>6} {s['win_rate'] * 100:>5.1f}% "
            f"{s['avg_win']:>+8.2f} {s['avg_loss']:>+8.2f} "
            f"{s['expectancy']:>+8.2f} {s['profit_factor']:>6.2f} "
            f"{s['total_pnl']:>+9.2f} {s['max_drawdown'] * 100:>6.2f}%")

    return summaries


def task_6_out_of_sample(all_data):
    log("\n" + "=" * 80)
    log("TASK 6: OUT-OF-SAMPLE TESTING")
    log("=" * 80)

    log(f"\nData split:")
    log(f"  Training:   days 0–{TRAIN_END} (~{TRAIN_END} days)")
    log(f"  Validation: days {TRAIN_END}–{VAL_END} (~{VAL_END - TRAIN_END} days)")
    log(f"  Test:       days {TEST_START}–{N_DAYS} (~{N_DAYS - TEST_START} days)")

    experiments = {
        "A: Baseline": StrategyEngine(),
        "B: No CHOP": ExperimentB_NoCHOP(),
        "C: TREND only": ExperimentC_TrendOnly(),
        "D: TP at 2R": ExperimentD_TP2R(),
        "E: TP at 1.5R": ExperimentE_TP1_5R(),
        "F: Graduated risk": ExperimentF_GraduatedRisk(),
        "G: Early Trend": ExperimentG_EarlyTrend(),
    }

    periods = {
        "Training": slice(0, TRAIN_END),
        "Validation": slice(TRAIN_END - 200, VAL_END),
        "Test": slice(TEST_START - 200, N_DAYS),
    }

    for period_name, period_slice in periods.items():
        log(f"\n--- {period_name} Period ---")
        log(f"{'Experiment':<22} {'Trades':>6} {'Win%':>6} {'Expect':>8} {'PF':>6} {'PnL':>9}")
        log("-" * 65)

        for exp_name, engine in experiments.items():
            results = run_ablation_experiment(engine, exp_name, all_data, period_slice)
            summary = summarize_experiment(exp_name, results)
            log(f"{summary['name']:<22} {summary['trades']:>6} "
                f"{summary['win_rate'] * 100:>5.1f}% "
                f"{summary['expectancy']:>+8.2f} {summary['profit_factor']:>6.2f} "
                f"{summary['total_pnl']:>+9.2f}")


def task_7_per_asset_analysis(all_data):
    log("\n" + "=" * 80)
    log("TASK 7: PER-ASSET AND PORTFOLIO ANALYSIS")
    log("=" * 80)

    engine = StrategyEngine()

    log(f"\n--- Individual Asset Results (Baseline) ---")
    log(f"{'Asset':<10} {'Trades':>6} {'Win%':>6} {'Expect':>8} {'PF':>6} "
        f"{'PnL':>9} {'MaxDD':>7} {'Final$':>8}")
    log("-" * 75)

    asset_results = {}
    for symbol in ASSETS:
        result = run_enhanced_backtest(engine, symbol, all_data[symbol], "Conservative")
        asset_results[symbol] = result

        wins = result.wins
        total = result.total_trades
        wr = wins / total if total > 0 else 0
        pnls = [t.pnl for t in result.trades]
        avg_w = np.mean([p for p in pnls if p > 0]) if any(p > 0 for p in pnls) else 0
        avg_l = np.mean([p for p in pnls if p <= 0]) if any(p <= 0 for p in pnls) else 0
        exp = wr * avg_w + (1 - wr) * avg_l if total > 0 else 0
        gw = sum(p for p in pnls if p > 0)
        gl = abs(sum(p for p in pnls if p <= 0))
        pf = gw / gl if gl > 0 else float('inf')

        log(f"{symbol:<10} {total:>6} {wr * 100:>5.1f}% {exp:>+8.2f} "
            f"{pf:>6.2f} {result.total_pnl:>+9.2f} "
            f"{result.max_drawdown_pct * 100:>6.2f}% {result.final_balance:>8.2f}")

    # Portfolio combinations
    log(f"\n--- Portfolio Combinations ---")
    combos = {
        "BTC+ETH": ["BTC/USD", "ETH/USD"],
        "BTC+ETH+LINK": ["BTC/USD", "ETH/USD", "LINK/USD"],
        "All 5": ASSETS,
    }

    for combo_name, symbols in combos.items():
        total_trades = sum(asset_results[s].total_trades for s in symbols)
        total_wins = sum(asset_results[s].wins for s in symbols)
        total_pnl = sum(asset_results[s].total_pnl for s in symbols)
        max_dd = max(asset_results[s].max_drawdown_pct for s in symbols)
        all_pnls = []
        for s in symbols:
            all_pnls.extend([t.pnl for t in asset_results[s].trades])

        wr = total_wins / total_trades if total_trades > 0 else 0
        avg_w = np.mean([p for p in all_pnls if p > 0]) if any(p > 0 for p in all_pnls) else 0
        avg_l = np.mean([p for p in all_pnls if p <= 0]) if any(p <= 0 for p in all_pnls) else 0
        exp = wr * avg_w + (1 - wr) * avg_l if total_trades > 0 else 0
        gw = sum(p for p in all_pnls if p > 0)
        gl = abs(sum(p for p in all_pnls if p <= 0))
        pf = gw / gl if gl > 0 else float('inf')

        log(f"{combo_name:<15} {total_trades:>6} {wr * 100:>5.1f}% {exp:>+8.2f} "
            f"{pf:>6.2f} {total_pnl:>+9.2f} {max_dd * 100:>6.2f}%")


def task_8_challenge_simulation(all_data):
    log("\n" + "=" * 80)
    log("TASK 8: CHALLENGE-SPECIFIC MONTE CARLO SIMULATION")
    log("=" * 80)

    experiments = {
        "A: Baseline": StrategyEngine(),
        "B: No CHOP": ExperimentB_NoCHOP(),
        "C: TREND only": ExperimentC_TrendOnly(),
        "D: TP at 2R": ExperimentD_TP2R(),
        "E: TP at 1.5R": ExperimentE_TP1_5R(),
        "F: Graduated risk": ExperimentF_GraduatedRisk(),
        "G: Early Trend": ExperimentG_EarlyTrend(),
    }

    n_sims = 200

    log(f"\nMonte Carlo: {n_sims} simulations per experiment per asset")
    log(f"Window: 90 tradeable days per simulation")
    log(f"Pass: balance >= $1,120 | Fail: balance <= $950")

    log(f"\n{'Experiment':<22} {'Pass%':>6} {'Fail%':>6} {'Neutral%':>8} "
        f"{'AvgBal':>8} {'MedPnL':>8} {'AvgDD':>6} {'AvgTrd':>7}")
    log("-" * 85)

    for exp_name, engine in experiments.items():
        all_passes = 0
        all_fails = 0
        all_finals = []
        all_pnls = []
        all_dds = []
        all_trade_counts = []
        total_sims = 0

        for symbol in ASSETS:
            df = all_data[symbol]
            mc = run_monte_carlo(engine, symbol, df, exp_name,
                                 n_simulations=n_sims // len(ASSETS),
                                 window_days=90)
            if mc["n_simulations"] > 0:
                all_passes += int(mc["pass_rate"] * mc["n_simulations"])
                all_fails += int(mc["fail_rate"] * mc["n_simulations"])
                total_sims += mc["n_simulations"]
                all_finals.append(mc["avg_final_balance"])
                all_dds.append(mc["avg_max_drawdown"])
                all_trade_counts.append(mc["avg_trades"])
                if "results" in mc:
                    all_pnls.extend([r.total_pnl for r in mc["results"]])

        pass_rate = all_passes / total_sims if total_sims > 0 else 0
        fail_rate = all_fails / total_sims if total_sims > 0 else 0
        neutral_rate = 1 - pass_rate - fail_rate
        avg_final = np.mean(all_finals) if all_finals else 1000
        med_pnl = np.median(all_pnls) if all_pnls else 0
        avg_dd = np.mean(all_dds) if all_dds else 0
        avg_trades = np.mean(all_trade_counts) if all_trade_counts else 0

        log(f"{exp_name:<22} {pass_rate * 100:>5.1f}% {fail_rate * 100:>5.1f}% "
            f"{neutral_rate * 100:>7.1f}% {avg_final:>8.2f} {med_pnl:>+8.2f} "
            f"{avg_dd * 100:>5.2f}% {avg_trades:>7.1f}")

    if all_pnls:
        log(f"\n--- Distribution Statistics (last experiment) ---")
        log(f"  5th percentile PnL:  {np.percentile(all_pnls, 5):>+.2f}")
        log(f"  25th percentile PnL: {np.percentile(all_pnls, 25):>+.2f}")
        log(f"  Median PnL:          {np.median(all_pnls):>+.2f}")
        log(f"  75th percentile PnL: {np.percentile(all_pnls, 75):>+.2f}")
        log(f"  95th percentile PnL: {np.percentile(all_pnls, 95):>+.2f}")


def task_9_decision_criteria(summaries_full, summaries_oos):
    log("\n" + "=" * 80)
    log("TASK 9: DECISION CRITERIA EVALUATION")
    log("=" * 80)

    log("\nCriteria for proceeding to paper testing:")
    log("  1. Positive expectancy (out of sample)")
    log("  2. Profit factor > 1.0 (out of sample)")
    log("  3. Better challenge pass probability than baseline")
    log("  4. Max drawdown compatible with 5% failure boundary")
    log("  5. Not dependent on one asset or short period")
    log("  6. Enough trades for statistical significance")

    log(f"\n{'Experiment':<22} {'Expect':>8} {'PF':>6} {'Trades':>6} "
        f"{'Pass?':>6} {'Notes':<35}")
    log("-" * 95)

    for s in summaries_full:
        passes = []
        fails = []

        if s['expectancy'] > 0:
            passes.append("E+")
        else:
            fails.append("E-")

        if s['profit_factor'] > 1.0:
            passes.append("PF>1")
        else:
            fails.append("PF<1")

        if s['trades'] >= 20:
            passes.append("N>=20")
        else:
            fails.append("N<20")

        if s['max_drawdown'] < 0.05:
            passes.append("DD<5%")
        else:
            fails.append("DD>=5%")

        all_pass = len(fails) == 0
        notes = f"PASS: {', '.join(passes)}" if all_pass else f"FAIL: {', '.join(fails)}"

        log(f"{s['name']:<22} {s['expectancy']:>+8.2f} {s['profit_factor']:>6.2f} "
            f"{s['trades']:>6} {'YES' if all_pass else 'NO':>6} {notes:<35}")


def task_10_recommendation(summaries):
    log("\n" + "=" * 80)
    log("TASK 10: FINAL RECOMMENDATION")
    log("=" * 80)

    baseline = summaries[0]

    best = max(summaries, key=lambda s: s['expectancy'])
    best_pf = max(summaries, key=lambda s: s['profit_factor'] if s['profit_factor'] != float('inf') else 0)

    log(f"\n--- Summary of Evidence ---")
    log(f"")
    log(f"Baseline (A) performance:")
    log(f"  Trades:        {baseline['trades']}")
    log(f"  Win rate:      {baseline['win_rate'] * 100:.1f}%")
    log(f"  Expectancy:    {baseline['expectancy']:+.2f}")
    log(f"  Profit factor: {baseline['profit_factor']:.2f}")
    log(f"  Total PnL:     {baseline['total_pnl']:+.2f}")
    log(f"")

    positive_exp = [s for s in summaries if s['expectancy'] > 0]
    log(f"Experiments with positive expectancy: {len(positive_exp)}/{len(summaries)}")
    for s in positive_exp:
        log(f"  {s['name']}: E={s['expectancy']:+.2f}, PF={s['profit_factor']:.2f}")

    log(f"\nBest expectancy: {best['name']} ({best['expectancy']:+.2f})")
    log(f"Best PF:         {best_pf['name']} ({best_pf['profit_factor']:.2f})")

    log(f"\n--- RECOMMENDATION ---")
    log(f"")

    if baseline['expectancy'] > 0 and baseline['profit_factor'] > 1.0:
        log("The baseline strategy shows positive expectancy on synthetic data.")
        log("However, ALL results are from SYNTHETIC data only.")
    elif any(s['expectancy'] > 0 for s in summaries[1:]):
        improving = [s for s in summaries[1:] if s['expectancy'] > baseline['expectancy']]
        if improving:
            log(f"The following modifications improved over baseline:")
            for s in improving:
                log(f"  {s['name']}: expectancy {s['expectancy']:+.2f} vs baseline {baseline['expectancy']:+.2f}")
    else:
        log("No experiment shows reliably positive expectancy.")
        log("The strategy may need fundamental redesign.")

    log(f"\n--- CRITICAL CAVEATS ---")
    log(f"")
    log("1. ALL results are from SYNTHETIC data.")
    log("   Real market data must be used before any production decision.")
    log("")
    log("2. The strategy specification claims trend-only entry, but the code")
    log("   allows CHOP and LOWVOL entries. This mismatch must be resolved")
    log("   as a deliberate design decision, not left ambiguous.")
    log("")
    log("3. Sample sizes may be too small for statistical significance.")
    log("   With fewer than ~30 trades per variant, confidence intervals")
    log("   are wide and results may be noise.")
    log("")
    log("4. Before implementing ANY changes:")
    log("   a. Fetch real historical data from Kraken/Coinbase APIs")
    log("   b. Re-run this study on real data")
    log("   c. Validate with walk-forward analysis")
    log("   d. Paper trade any promising variant for >= 30 days")
    log("")
    log("5. NEXT ACTION: Obtain real market data access, then re-run this study.")
    log("   Do NOT modify production strategy based on synthetic results alone.")

    log(f"\n--- NO PRODUCTION CODE WAS MODIFIED ---")
    log(f"--- ALL CHANGES ARE IN research/ DIRECTORY ONLY ---")


def main():
    log("=" * 80)
    log("CONTROLLED STRATEGY RESEARCH STUDY")
    log("=" * 80)
    log(f"Date: 2026-07-15")
    log(f"Data: SYNTHETIC (no API access available)")
    log(f"Assets: {', '.join(ASSETS)}")
    log(f"Period: {N_DAYS} days")
    log(f"Strategy: Conservative (StrategyEngine)")
    log(f"")
    log("WARNING: All results are from synthetic data.")
    log("Do not draw production conclusions from these results.")
    log("=" * 80)

    log("\nGenerating synthetic market data...")
    all_data = generate_all_assets(n_days=N_DAYS, base_seed=42)
    for symbol, df in all_data.items():
        log(f"  {symbol}: {len(df)} candles, "
            f"price {df['close'].iloc[0]:.2f} → {df['close'].iloc[-1]:.2f}")

    task_1_validate_diagnostic(all_data)
    task_2_reconcile_contradiction(all_data)
    task_3_diagnose_stoploss(all_data)
    task_4_diagnose_takeprofit(all_data)
    summaries_full = task_5_ablation_experiments(all_data)
    task_6_out_of_sample(all_data)
    task_7_per_asset_analysis(all_data)
    task_8_challenge_simulation(all_data)

    # For OOS summaries, use test period
    test_summaries = []
    experiments_for_oos = {
        "A: Baseline": StrategyEngine(),
        "B: No CHOP": ExperimentB_NoCHOP(),
        "C: TREND only": ExperimentC_TrendOnly(),
        "D: TP at 2R": ExperimentD_TP2R(),
        "E: TP at 1.5R": ExperimentE_TP1_5R(),
        "F: Graduated risk": ExperimentF_GraduatedRisk(),
        "G: Early Trend": ExperimentG_EarlyTrend(),
    }
    for exp_name, engine in experiments_for_oos.items():
        results = run_ablation_experiment(engine, exp_name, all_data,
                                           slice(TEST_START - 200, N_DAYS))
        test_summaries.append(summarize_experiment(exp_name, results))

    task_9_decision_criteria(summaries_full, test_summaries)
    task_10_recommendation(summaries_full)

    report_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                "RESEARCH_REPORT.txt")
    with open(report_path, "w") as f:
        f.write(report.getvalue())
    log(f"\nReport saved to: {report_path}")


if __name__ == "__main__":
    main()
